//go:build !cgo

package robotgo

// Portable key names remain available when native keyboard injection is not
// compiled. Values match the CGO build's public constants.
const (
	KeyB = "b"
	KeyC = "c"
	KeyD = "d"
	KeyE = "e"
	KeyF = "f"
	KeyG = "g"
	KeyH = "h"
	KeyJ = "j"
	KeyK = "k"
	KeyL = "l"
	KeyM = "m"
	KeyN = "n"
	KeyO = "o"
	KeyP = "p"
	KeyQ = "q"
	KeyR = "r"
	KeyS = "s"
	KeyT = "t"
	KeyU = "u"
	KeyV = "v"
	KeyW = "w"
	KeyX = "x"
	KeyY = "y"
	KeyZ = "z"

	CapA = "A"
	CapB = "B"
	CapC = "C"
	CapD = "D"
	CapE = "E"
	CapF = "F"
	CapG = "G"
	CapH = "H"
	CapI = "I"
	CapJ = "J"
	CapK = "K"
	CapL = "L"
	CapM = "M"
	CapN = "N"
	CapO = "O"
	CapP = "P"
	CapQ = "Q"
	CapR = "R"
	CapS = "S"
	CapT = "T"
	CapU = "U"
	CapV = "V"
	CapW = "W"
	CapX = "X"
	CapY = "Y"
	CapZ = "Z"

	Key0 = "0"
	Key1 = "1"
	Key2 = "2"
	Key3 = "3"
	Key4 = "4"
	Key5 = "5"
	Key6 = "6"
	Key7 = "7"
	Key8 = "8"
	Key9 = "9"

	Backspace = "backspace"
	Delete    = "delete"
	Tab       = "tab"
	Esc       = "esc"
	Escape    = "escape"
	Up        = "up"
	Down      = "down"
	Right     = "right"
	Left      = "left"
	Home      = "home"
	End       = "end"
	Pageup    = "pageup"
	Pagedown  = "pagedown"

	F1  = "f1"
	F2  = "f2"
	F3  = "f3"
	F4  = "f4"
	F5  = "f5"
	F6  = "f6"
	F7  = "f7"
	F8  = "f8"
	F9  = "f9"
	F10 = "f10"
	F11 = "f11"
	F12 = "f12"
	F13 = "f13"
	F14 = "f14"
	F15 = "f15"
	F16 = "f16"
	F17 = "f17"
	F18 = "f18"
	F19 = "f19"
	F20 = "f20"
	F21 = "f21"
	F22 = "f22"
	F23 = "f23"
	F24 = "f24"

	Lcmd        = "lcmd"
	Rcmd        = "rcmd"
	Lalt        = "lalt"
	Ralt        = "ralt"
	Ctrl        = "ctrl"
	Lctrl       = "lctrl"
	Rctrl       = "rctrl"
	Control     = "control"
	Shift       = "shift"
	Lshift      = "lshift"
	Rshift      = "rshift"
	Capslock    = "capslock"
	Space       = "space"
	Print       = "print"
	Printscreen = "printscreen"
	Insert      = "insert"
	Menu        = "menu"

	AudioMute    = "audio_mute"
	AudioVolDown = "audio_vol_down"
	AudioVolUp   = "audio_vol_up"
	AudioPlay    = "audio_play"
	AudioStop    = "audio_stop"
	AudioPause   = "audio_pause"
	AudioPrev    = "audio_prev"
	AudioNext    = "audio_next"
	AudioRewind  = "audio_rewind"
	AudioForward = "audio_forward"
	AudioRepeat  = "audio_repeat"
	AudioRandom  = "audio_random"

	Num0       = "num0"
	Num1       = "num1"
	Num2       = "num2"
	Num3       = "num3"
	Num4       = "num4"
	Num5       = "num5"
	Num6       = "num6"
	Num7       = "num7"
	Num8       = "num8"
	Num9       = "num9"
	NumLock    = "num_lock"
	ScrollLock = "scroll_lock"
	PauseBreak = "pause_break"
	NumDecimal = "num."
	NumPlus    = "num+"
	NumMinus   = "num-"
	NumMul     = "num*"
	NumDiv     = "num/"
	NumClear   = "num_clear"
	NumEnter   = "num_enter"
	NumEqual   = "num_equal"

	LightsMonUp     = "lights_mon_up"
	LightsMonDown   = "lights_mon_down"
	LightsKbdToggle = "lights_kbd_toggle"
	LightsKbdUp     = "lights_kbd_up"
	LightsKbdDown   = "lights_kbd_down"
)
