#!/usr/bin/env bash

readonly ROBOTGO_HYPRLAND_FAILURE_STAGE_COMPOSITOR_START='compositor-start'
readonly ROBOTGO_HYPRLAND_FAILURE_STAGE_CONTAINER_RUNTIME='container-runtime'
readonly ROBOTGO_HYPRLAND_FAILURE_STAGE_OUTPUT_TOPOLOGY='output-topology'
readonly ROBOTGO_HYPRLAND_FAILURE_STAGE_INDUCED_FAILURE='induced-failure'
readonly ROBOTGO_HYPRLAND_FAILURE_STAGE_PREFLIGHT='preflight'
readonly ROBOTGO_HYPRLAND_FAILURE_STAGE_INTEGRATION_TEST='integration-test'
readonly ROBOTGO_HYPRLAND_FAILURE_STAGE_FINALIZE='finalize'
readonly ROBOTGO_HYPRLAND_FAILURE_STAGE_VERIFY='verify'
readonly ROBOTGO_HYPRLAND_FAILURE_STAGE_SUMMARY='summary'

readonly -a ROBOTGO_HYPRLAND_FAILURE_STAGES=(
	"$ROBOTGO_HYPRLAND_FAILURE_STAGE_COMPOSITOR_START"
	"$ROBOTGO_HYPRLAND_FAILURE_STAGE_CONTAINER_RUNTIME"
	"$ROBOTGO_HYPRLAND_FAILURE_STAGE_OUTPUT_TOPOLOGY"
	"$ROBOTGO_HYPRLAND_FAILURE_STAGE_INDUCED_FAILURE"
	"$ROBOTGO_HYPRLAND_FAILURE_STAGE_PREFLIGHT"
	"$ROBOTGO_HYPRLAND_FAILURE_STAGE_INTEGRATION_TEST"
	"$ROBOTGO_HYPRLAND_FAILURE_STAGE_FINALIZE"
	"$ROBOTGO_HYPRLAND_FAILURE_STAGE_VERIFY"
	"$ROBOTGO_HYPRLAND_FAILURE_STAGE_SUMMARY"
)

robotgo_hyprland_failure_stage_is_allowed() {
	local candidate="$1"
	local stage
	for stage in "${ROBOTGO_HYPRLAND_FAILURE_STAGES[@]}"; do
		[[ "$candidate" == "$stage" ]] && return 0
	done
	return 1
}
