name: Go
on: [push]

# Avoid canceling in-progress jobs when a new push arrives
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go 1.24.0
        uses: actions/setup-go@v4
        with:
          go-version: 1.24.0
      - name: Install system dependencies for cgo typecheck
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential pkg-config \
            libx11-dev libxtst-dev \
            libwayland-dev libxkbcommon-dev wayland-protocols
      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - name: Add golangci-lint to PATH
        run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Run golangci-lint
        run: CGO_ENABLED=1 golangci-lint run --timeout=5m ./...
  test:
    # name: build
    strategy:
      fail-fast: false
      matrix:
        # go: [1.12.x, 1.13.x]
        os: [macOS-latest, windows-latest] # ubuntu-latest
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Go 1.24.0
        uses: actions/setup-go@v4
        with:
          go-version: 1.24.0
        id: go

      - name: Get dependencies
        run: |
          go mod download

      - name: Build
        run: go build -v .
      - name: Test
        run: go test -v robot_info_test.go
        # run: go test -v .
